#!/usr/bin/env python3
"""CoP/DCM stabilizer for sustained walking on the faithful centroidal recovery.

The open-loop DCM controller (run_gait_dcm.py) tracks a CoM *position* reference
with the normalized MPC; on a single foot that feedback is too slow, a ~10 cm
lag builds up, and the robot tips. This module closes the loop on the *divergent
component of motion* directly (the standard capture-point / DCM stabilizer):

    xi      = c + c_dot / omega                       (measured DCM)
    p_cmd   = p_ref + (1 + k_dcm/omega) (xi - xi_ref)  (DCM control law)
    p_cmd  <- clamp(p_cmd, support polygon)            (CoP limit)
    c_ddot_des = omega^2 (c - p_cmd)                   (LIPM -> CoM acceleration)

The commanded ZMP is placed *outside* the CoM to drive the DCM error to zero
(closed loop xi_dot - xi_dot_ref = -k_dcm (xi - xi_ref)); clamping p_cmd to the
stance-foot polygon is the CoP constraint. The resulting CoM acceleration is
realized by the SAME faithful centroidal-wrench recovery (CoM-acceleration
objective) and the swing foot tracks its lift-and-place task. An offset-free
disturbance term is added for push rejection. The interaction-dynamics recovery
is unchanged; only the body-port command is generated by the DCM law, which is
the appropriate residual-acceleration policy for locomotion.

Usage:
  MPLCONFIGDIR=/private/tmp/mplconfig python3 run_gait_dcm_stab.py --step-len 0.06 --n-steps 10
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import mujoco
import numpy as np

from normalized_mpc import RandomWalkDisturbanceObserver
from run_g1_root_assist_demo import ACTUATED_JOINT_NAMES, robot_com, roll_pitch_yaw_from_body
from run_g1_torque_realizer_benchmark import (
    InverseDynamicsQPRealizer, TORQUE_STAND_CTRL,
    body_id, generate_torque_model, hand_state, joint_id, site_id,
)
from run_gait_dcm import DCMWalk

HERE = Path(__file__).resolve().parent
RESULTS = HERE / "results"; RESULTS.mkdir(exist_ok=True)
SIM_DT = 0.001
COMMAND_DT = 0.002

# Support-polygon half-extents used for the CoP clamp (stance-foot frame ~ site).
COP_HALF = np.array([0.06, 0.025])


def com_velocity(model, data, root):
    """Momentum-based whole-body CoM velocity (subtree linear velocity)."""
    mujoco.mj_subtreeVel(model, data)
    return data.subtree_linvel[root].copy()


def cop_clamp(p_cmd, stance, foot_xy):
    if len(stance) == 2:
        xs = [foot_xy[f][0] for f in stance]; ys = [foot_xy[f][1] for f in stance]
        lo = np.array([min(xs) - COP_HALF[0], min(ys) - COP_HALF[1]])
        hi = np.array([max(xs) + COP_HALF[0], max(ys) + COP_HALF[1]])
    else:
        c = foot_xy[stance[0]]
        lo = c - COP_HALF; hi = c + COP_HALF
    return np.clip(p_cmd, lo, hi)


def run(step_len=0.06, n_steps=10, t_step=0.62, t_ds=0.15, lift_h=0.05,
        k_dcm=3.0, zmp_y_scale=1.0, push=False, duration=None, observer=True, seed=0):
    model = mujoco.MjModel.from_xml_path(str(generate_torque_model()))
    model.opt.timestep = SIM_DT
    data = mujoco.MjData(model)
    mujoco.mj_resetDataKeyframe(model, data, 0)
    for v, n in zip(TORQUE_STAND_CTRL, ACTUATED_JOINT_NAMES):
        data.qpos[model.jnt_qposadr[joint_id(model, n)]] = v
    mujoco.mj_forward(model, data)

    realizer = InverseDynamicsQPRealizer(model)
    torso = body_id(model, "torso_link"); pelvis = body_id(model, "pelvis")
    hand_sid = site_id(model, "right_hand_site")
    lsid = site_id(model, "left_foot"); rsid = site_id(model, "right_foot")
    foot_sid = {"left": lsid, "right": rsid}
    left0 = data.site_xpos[lsid][:2].copy(); right0 = data.site_xpos[rsid][:2].copy()
    ground_z = float(min(data.site_xpos[lsid][2], data.site_xpos[rsid][2]))
    com0 = robot_com(model, data); z_c = float(com0[2] - ground_z)
    hand0, _, _ = hand_state(model, data, hand_sid)
    base_h = float(data.qpos[2]); q_nom = TORQUE_STAND_CTRL.copy(); qd0 = np.zeros_like(q_nom)

    plan = DCMWalk(left0, right0, step_len, n_steps, z_c, t_step, t_ds, t_settle=0.8,
                   zmp_y_scale=zmp_y_scale)
    omega = plan.w
    if duration is None:
        duration = plan.total + 0.8

    task_obs = RandomWalkDisturbanceObserver(dim=3, dt=COMMAND_DT, q_d=0.3, r_y=1e-4)
    d_com = np.zeros(2)                      # offset-free CoM-accel disturbance
    d_task = np.zeros(3); u_task = np.zeros(3)
    com_acc_des = np.zeros(3); task_acc_des = np.zeros(3); swing_cmd = None
    stance_prev = (); stance_targets = {}; swing_prev = None; last_sw_target = None
    dcm_lp = np.zeros(2)                     # low-passed DCM-error integral (offset-free)

    N = int(duration / SIM_DT); period = max(1, int(COMMAND_DT / SIM_DT))
    log = {k: np.zeros((N, d)) for k, d in
           [("t", 1), ("com", 2), ("xi", 2), ("xi_ref", 2), ("zmp", 2), ("pcmd", 2),
            ("footz", 2), ("rpy", 2)]}
    log["nstance"] = np.zeros(N); log["height"] = np.zeros(N); fell = False; switches = 0

    for k in range(N):
        t = k * SIM_DT
        com = robot_com(model, data)
        rpy = roll_pitch_yaw_from_body(data, torso)
        hand, handv, handj = hand_state(model, data, hand_sid)
        stance, swing, s, sw_start, sw_target = plan.schedule(t)

        if swing_prev is not None and swing is None and last_sw_target is not None:
            plan.commit_plant(swing_prev, last_sw_target)
        swing_prev = swing
        if swing is not None:
            last_sw_target = sw_target

        if stance != stance_prev:
            if stance_prev != ():
                switches += 1
            cur = realizer.contact_points(model, data, stance)
            for key, (pos, _) in cur.items():
                foot = key.split("_", 1)[0]
                if foot not in stance_prev or key not in stance_targets:
                    stance_targets[key] = pos.copy()
            for key in list(stance_targets):
                if key not in cur:
                    del stance_targets[key]
            stance_prev = stance
        stance_contacts = realizer.contact_points(model, data, stance)

        xi_ref, zmp_ref = plan.xi_and_zmp(t)
        if k % period == 0:
            cv = com_velocity(model, data, pelvis)[:2]
            xi_meas = com[:2] + cv / omega
            # DCM control law -> commanded ZMP, clamped to the support polygon
            p_cmd = zmp_ref + (1.0 + k_dcm / omega) * (xi_meas - xi_ref)
            foot_xy = {"left": data.site_xpos[lsid][:2].copy(), "right": data.site_xpos[rsid][:2].copy()}
            p_cmd = cop_clamp(p_cmd, stance, foot_xy)
            # offset-free: integrate residual DCM error (rejects sustained bias/push)
            if observer:
                dcm_lp = 0.995 * dcm_lp + 0.005 * (xi_meas - xi_ref)
            com_acc_xy = omega ** 2 * (com[:2] - p_cmd) - (omega * k_dcm) * dcm_lp
            com_acc_des = np.array([com_acc_xy[0], com_acc_xy[1], 0.0])

            hand_ref = hand0 + np.array([0.0, 0.03 * np.sin(2 * np.pi * 0.35 * t), 0.0])
            hand_v_ref = np.array([0.0, 0.03 * 2 * np.pi * 0.35 * np.cos(2 * np.pi * 0.35 * t), 0.0])
            hand_a_ref = np.array([0.0, -0.03 * (2 * np.pi * 0.35) ** 2 * np.sin(2 * np.pi * 0.35 * t), 0.0])
            x_task = np.r_[hand - hand_ref, handv - hand_v_ref]
            u_task = _task_solve(x_task, d_task)
            d_task, _ = task_obs.step(hand - hand_ref, u_task)
            task_acc_des = hand_a_ref + u_task

            swing_cmd = None
            if swing is not None:
                sid = foot_sid[swing]
                xy = sw_start + (sw_target - sw_start) * (0.5 - 0.5 * np.cos(np.pi * s))
                z = ground_z + lift_h * np.sin(np.pi * s)
                swing_cmd = dict(sid=sid, pos_des=np.array([xy[0], xy[1], z]),
                                 vel_des=np.zeros(3), kp=280.0, kd=32.0, weight=14.0)
            p_cmd_log = p_cmd

        data.xfrc_applied[:] = 0.0
        if push and (0.55 * duration) <= t < (0.55 * duration + 0.1):
            data.xfrc_applied[pelvis, :3] = np.array([0.0, 40.0, 0.0])

        realizer.command(model, data, q_nom, qd0, np.zeros(2), task_acc_des, handj,
                          stance_contacts, stance_targets, base_h, rpy,
                          com_acc_des=com_acc_des, swing_task=swing_cmd)
        mujoco.mj_step(model, data); mujoco.mj_forward(model, data)

        log["t"][k] = float(data.time); log["com"][k] = robot_com(model, data)[:2]
        log["xi"][k] = com[:2] + com_velocity(model, data, pelvis)[:2] / omega
        log["xi_ref"][k] = xi_ref; log["zmp"][k] = zmp_ref; log["pcmd"][k] = p_cmd_log
        log["footz"][k] = [data.site_xpos[lsid][2], data.site_xpos[rsid][2]]
        log["rpy"][k] = roll_pitch_yaw_from_body(data, torso)[:2]
        log["nstance"][k] = len(stance); log["height"][k] = data.qpos[2]
        if data.qpos[2] < 0.45 or np.max(np.abs(log["rpy"][k])) > 0.7:
            fell = True
            for arr in log.values():
                arr[k + 1:] = arr[k]
            break

    end = k
    ss = slice(int(0.8 / SIM_DT), end)
    dcm_rms = float(1000 * np.sqrt(np.mean(np.sum((log["xi"][ss] - log["xi_ref"][ss]) ** 2, axis=1)))) if end > int(0.8 / SIM_DT) else float("nan")
    summary = dict(
        step_len=step_len, n_steps=n_steps, t_step=t_step, k_dcm=k_dcm, push=push,
        observer=observer, fell=fell, completed_s=float(log["t"][end, 0]),
        planned_s=float(plan.total), completed_full_plan=bool((not fell) and log["t"][end, 0] >= plan.total - 0.05),
        contact_switches=int(switches),
        forward_travel_m=float(log["com"][end, 0] - log["com"][0, 0]),
        dcm_tracking_rms_mm=dcm_rms,
        left_max_lift_mm=float(1000 * (log["footz"][:end + 1, 0].max() - ground_z)) if end > 0 else 0.0,
        right_max_lift_mm=float(1000 * (log["footz"][:end + 1, 1].max() - ground_z)) if end > 0 else 0.0,
        max_roll_pitch_rad=float(np.max(np.abs(log["rpy"][:end + 1]))) if end > 0 else 0.0,
        min_pelvis_height_m=float(np.min(log["height"][:end + 1])) if end > 0 else 0.0,
        z_c=z_c, omega=omega,
    )
    return log, summary, ground_z


# task port: a tiny normalized regulator so the arm holds while walking
from normalized_mpc import NormalizedMPC as _NMPC
_TASK = _NMPC(dim=3, dt=COMMAND_DT, horizon=18, q_pos=120.0, q_vel=12.0, r=0.1, u_max=np.array([8.0, 8.0, 8.0]))
def _task_solve(x, d):
    return _TASK.solve(x, d)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--step-len", type=float, default=0.06)
    ap.add_argument("--n-steps", type=int, default=10)
    ap.add_argument("--t-step", type=float, default=0.62)
    ap.add_argument("--k-dcm", type=float, default=3.0)
    ap.add_argument("--push", action="store_true")
    args = ap.parse_args()
    log, summ, gz = run(step_len=args.step_len, n_steps=args.n_steps, t_step=args.t_step,
                        k_dcm=args.k_dcm, push=args.push)
    print(json.dumps(summ, indent=2))

    fig, ax = plt.subplots(3, 1, figsize=(10, 9), sharex=True)
    ax[0].plot(log["t"], log["xi"][:, 1], label="DCM y"); ax[0].plot(log["t"], log["xi_ref"][:, 1], "--", label="DCM y ref")
    ax[0].plot(log["t"], log["pcmd"][:, 1], ":", label="ZMP cmd", alpha=.6)
    ax[0].set_ylabel("lateral y [m]"); ax[0].legend(fontsize=8); ax[0].grid(alpha=.3)
    ax[1].plot(log["t"], log["com"][:, 0], label="CoM x"); ax[1].set_ylabel("forward x [m]"); ax[1].legend(fontsize=8); ax[1].grid(alpha=.3)
    ax[2].plot(log["t"], 1000 * (log["footz"][:, 0] - gz), label="left foot")
    ax[2].plot(log["t"], 1000 * (log["footz"][:, 1] - gz), label="right foot")
    ax[2].set_ylabel("foot lift [mm]"); ax[2].set_xlabel("t [s]"); ax[2].legend(fontsize=8); ax[2].grid(alpha=.3)
    fig.suptitle(f"CoP/DCM stabilizer: switches={summ['contact_switches']} travel={summ['forward_travel_m']:.2f}m "
                 f"full_plan={summ['completed_full_plan']} fell={summ['fell']} DCM-RMS={summ['dcm_tracking_rms_mm']:.0f}mm")
    fig.tight_layout(); fig.savefig(RESULTS / "gait_dcm_stab.png", dpi=150)
    with (RESULTS / "gait_dcm_stab_summary.json").open("w") as f:
        json.dump(summ, f, indent=2)
    print("saved: results/gait_dcm_stab.png, results/gait_dcm_stab_summary.json")


if __name__ == "__main__":
    main()
